/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Supply extends javax.swing.JFrame {

    Connection con1 = null;
    public Supply() {
        initComponents();
        con1 = DBConnect.getconnection();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        supid = new javax.swing.JTextField();
        venid = new javax.swing.JTextField();
        drugid = new javax.swing.JTextField();
        quan = new javax.swing.JTextField();
        sdate = new com.toedter.calendar.JDateChooser();
        submit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supply ID");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 160, 35));

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vendor ID");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 38));

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Drug Code");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, 40));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Supplied Date");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, 35));

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantity");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 160, 35));

        supid.setBackground(new java.awt.Color(0, 0, 51));
        supid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supid.setForeground(new java.awt.Color(255, 255, 255));
        supid.setText("Enter Supply ID");
        supid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supidActionPerformed(evt);
            }
        });
        jPanel1.add(supid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 218, 40));

        venid.setBackground(new java.awt.Color(0, 0, 51));
        venid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        venid.setForeground(new java.awt.Color(255, 255, 255));
        venid.setText("Enter Vendor ID");
        venid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venidActionPerformed(evt);
            }
        });
        jPanel1.add(venid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 38));

        drugid.setBackground(new java.awt.Color(0, 0, 51));
        drugid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugid.setForeground(new java.awt.Color(255, 255, 255));
        drugid.setText("Enter Drug code");
        drugid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        drugid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugidActionPerformed(evt);
            }
        });
        jPanel1.add(drugid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 220, 40));

        quan.setBackground(new java.awt.Color(0, 0, 51));
        quan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quan.setForeground(new java.awt.Color(255, 255, 255));
        quan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanActionPerformed(evt);
            }
        });
        jPanel1.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 70, 35));

        sdate.setBackground(new java.awt.Color(0, 51, 51));
        sdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sdate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 150, 40));

        submit_btn.setBackground(new java.awt.Color(204, 204, 204));
        submit_btn.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(0, 153, 0));
        submit_btn.setText("Submit");
        submit_btn.setBorder(null);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 440, 110, 50));

        delete_btn.setBackground(new java.awt.Color(204, 204, 204));
        delete_btn.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 0, 0));
        delete_btn.setText("Delete");
        delete_btn.setBorder(null);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 110, 50));

        edit_btn.setBackground(new java.awt.Color(204, 204, 204));
        edit_btn.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(0, 0, 204));
        edit_btn.setText("Edit");
        edit_btn.setBorder(null);
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 110, 50));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supply ID", "Vendor ID", "Drug Code", "Supplied Date", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 550, 300));

        jLabel6.setBackground(new java.awt.Color(255, 204, 0));
        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Drug supply entry");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 356, 60));

        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/home.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 46, 46));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1120, 130));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front/small_close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 25, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1160, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
        PreparedStatement insert;
        
        private void table_update(){
            int c;
            try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            con1 = DriverManager.getConnection("jdbc:mysql://localhost/hospitaldb","root","");
            insert = con1.prepareStatement("select * from vendor_supply_drug");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            Df.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1;a<=c;a++){
                    v2.add(rs.getString("Supply_ID"));
                    v2.add(rs.getString("VendorID"));
                    v2.add(rs.getString("DrugCode"));
                    v2.add(rs.getString("Supplied_Date"));
                    v2.add(rs.getString("Quantity"));
                    
                }
                
                Df.addRow(v2);
            }
     
            
        }  catch (Exception ex) {
           
        }
            
        }
    private void supidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supidActionPerformed

    private void venidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venidActionPerformed

    private void drugidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugidActionPerformed

    private void quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
       String supplyID = supid.getText();
       String vendorID = venid.getText();
       String DrugCode = drugid.getText();
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String date = sdf.format(sdate.getDate());
       String quantity = quan.getText();
       
       
        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            con1 = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root","");
            insert = con1.prepareStatement("INSERT INTO `vendor_supply_drug`(`Supply_ID`, `VendorID`, `DrugCode`, `Supplied_Date`, `Quantity`) VALUES (?,?,?,?,?)");
            insert.setString(1, supplyID);
            insert.setString(2, vendorID);
            insert.setString(3, DrugCode);
            insert.setString(4, date);
            insert.setString(5, quantity);
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"record added");
            table_update();
            
            supid.setText("");
            venid.setText("");
            drugid.setText("");
            quan.setText("");
            supid.requestFocus();
             
            
        }catch(Exception e){
        } 
       
    }//GEN-LAST:event_submit_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        
        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        
        try {
            
           int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
 
           int dialogResult = JOptionPane.showConfirmDialog(null,"Do you want to delete the record","Warning",JOptionPane.YES_NO_OPTION);
           if(dialogResult == JOptionPane.YES_OPTION){
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                con1 = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root","");
                insert = con1.prepareStatement("delete from `vendor_supply_drug` WHERE Supply_ID =?");
                insert.setInt(1, id);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this,"RecordDeleted");
                table_update();
            
                supid.setText("");
                venid.setText("");
                drugid.setText("");
                quan.setText("");
                supid.requestFocus();
                
                
                
            } 
             
            
        } catch (Exception e) {
            
        }
        
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        
        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        try {
            
                int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
                String vendorID = venid.getText();
                String DrugCode = drugid.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(sdate.getDate());
                String quantity = quan.getText();
            
            
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                con1 = DriverManager.getConnection("jdbc:mysql://localhost/hospital","root","");
                insert = con1.prepareStatement("update `vendor_supply_drug` set VendorID=?,DrugCode=?,Supplied_Date=?,Quantity=? WHERE Supply_ID =?");
                insert.setString(1, vendorID);
                insert.setString(2, DrugCode);
                insert.setString(3, date);
                insert.setString(4, quantity);
                insert.setInt(5, id);
                insert.executeUpdate();

                JOptionPane.showMessageDialog(this,"Updated");
                table_update();

                supid.setText("");
                venid.setText("");
                drugid.setText("");
                quan.setText("");
                supid.requestFocus();
           
            
             
            
        } catch (Exception e) {
            
        }
        
        
        
    }//GEN-LAST:event_edit_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        try {
            DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            int selectedIndex = jTable1.getSelectedRow();
            
            supid.setText(Df.getValueAt(selectedIndex, 0).toString());
            venid.setText(Df.getValueAt(selectedIndex, 1).toString());
            drugid.setText(Df.getValueAt(selectedIndex, 2).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)Df.getValueAt(selectedIndex, 3));
            sdate.setDate(date);
            quan.setText(Df.getValueAt(selectedIndex, 4).toString());
        } catch (ParseException ex) {
            Logger.getLogger(Supply.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private int xMouse, yMouse;
    
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Home hm = new Home();
       hm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField drugid;
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField quan;
    private com.toedter.calendar.JDateChooser sdate;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField supid;
    private javax.swing.JTextField venid;
    // End of variables declaration//GEN-END:variables
}
